another way

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -256,12 +256,14 @@ jobs:
         if: "${{ success() || failure() }}"
         run: |
           docker compose exec -T app .github/actions/test_install.sh
-      - name: "WEB tests"
-        if: "${{ success() || failure() }}"
-        run: |
-          docker compose exec -T app .github/actions/test_tests-web.sh
-      - name: "Install Chrome"
+    #   - name: "WEB tests"
+    #     if: "${{ success() || failure() }}"
+    #     run: |
+    #       docker compose exec -T app .github/actions/test_tests-web.sh
+      - name: "Install chrome"
         uses: browser-actions/setup-chrome@v1
+        run: |
+          echo "Chrome installed"
       - name: "E2E tests"
         if: "${{ success() || failure() }}"
         id: "e2e"
